collections:
    - fronts
exclude:
    - 'README.md'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'jekyll.sh'
    - 'citations'
    - 'bootstrap'
defaults:
    - scope:
        path: ""
        type: "posts"
      values:
        excerpt_seperator: "<!--more-->"
        active: posts
