safe: True
exclude:
    - '/README.md'
    - '/Gemfile'
    - '/Gemfile.lock'
    - '/jekyll.sh'
    - '/node_modules/'
    - '/package.json'
    - '/build.py'
defaults:
    - scope:
        path: ""
        type: "posts"
      values:
        excerpt_seperator: "<!--more-->"
        active: posts
        layout: post

compress_html:
    clippings: all
    comments: all
